version: 2

defaults: &defaults
  docker:
  - image: circleci/node:10

jobs:
  test:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn test
    - run: yarn build
    - persist_to_workspace:
        root: .
        paths:
         - package.json
         - yarn.lock
         - .npmignore
         - dist
  deploy:
    <<: *defaults
    steps:
    - attach_workspace:
        at: .
    - run:
        name: List Workspace
        command: ls
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - run:
        name: Publish package
        command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
    - test:
        filters:
          tags:
            only: /^v.*/
    - deploy:
        requires:
        - test
        filters:
          branches:
            only: master
